[package]
name = "termesh"
version = "0.1.0"
authors = ["Daniele D'Orazio <d.dorazio96@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.2.7"
num-traits = "0.2.6"
structopt = "0.2.13"
termion = "1.5.1"

[dev-dependencies]
maplit = "1.0.1"
